name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Write .clasprc.json
        run: |
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Write .clasp.json
        run: |
          echo '{
            "scriptId": "${{ secrets.SCRIPT_ID }}",
            "rootDir": "./"
          }' > .clasp.json

      - name: Push to Google Apps Script
        run: clasp push --force

