on:
  push:
    branches:
      - hitanshu  # or change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clasp Action
        uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          accessToken: ${{ secrets.CLASP_ACCESS_TOKEN }}
          idToken: ""  # leave blank unless needed
          refreshToken: ${{ secrets.CLASP_REFRESH_TOKEN }}
          clientId: ${{ secrets.CLASP_CLIENT_ID }}
          clientSecret: ${{ secrets.CLASP_CLIENT_SECRET }}
          scriptId: ${{ secrets.CLASP_SCRIPT_ID }}
          command: "push"
          rootDir: ""  # set to your source dir
