on:
  push:
    branches:
      - test
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Test Environment
        if: github.ref == 'refs/heads/test'
        uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          accessToken: ${{ secrets.CLASP_ACCESS_TOKEN_TEST }}
          idToken: ""  # leave blank unless needed
          refreshToken: ${{ secrets.CLASP_REFRESH_TOKEN_TEST }}
          clientId: ${{ secrets.CLASP_CLIENT_ID_TEST }}
          clientSecret: ${{ secrets.CLASP_CLIENT_SECRET_TEST }}
          scriptId: ${{ secrets.CLASP_SCRIPT_ID_TEST }}
          command: "push"
          rootDir: ""  # set to your source dir

      - name: Deploy to Production Environment
        if: github.ref == 'refs/heads/main'
        uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          accessToken: ${{ secrets.CLASP_ACCESS_TOKEN }}
          idToken: ""  # leave blank unless needed
          refreshToken: ${{ secrets.CLASP_REFRESH_TOKEN }}
          clientId: ${{ secrets.CLASP_CLIENT_ID }}
          clientSecret: ${{ secrets.CLASP_CLIENT_SECRET }}
          scriptId: ${{ secrets.CLASP_SCRIPT_ID }}
          command: "push"
          rootDir: ""  # set to your source dir
