name: Deploy Google Apps Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          audience: https://token.actions.githubusercontent.com
          create_credentials_file: true
          export_environment_variables: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false

      - name: Generate .clasprc.json from GCP access token
        shell: bash
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
      
          echo "{
            \"token\": {
              \"access_token\": \"$ACCESS_TOKEN\",
              \"scope\": \"https://www.googleapis.com/auth/cloud-platform\",
              \"token_type\": \"Bearer\",
              \"expiry_date\": 9999999999999,
              \"id_token\": \"\"
            }
          }" > ~/.clasprc.json



      - name: Push to Google Apps Script
        run: clasp push --force
