name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Write service account credentials to file
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Authenticate clasp with service account
        run: clasp login --creds service-account.json

      - name: Set up .clasp.json
        run: |
          echo '{
            "scriptId": "${{ secrets.SCRIPT_ID }}",
            "rootDir": "./"
          }' > .clasp.json

      - name: Deploy to Google Apps Script
        run: clasp push --force

